import { LogisticStatus, OrderStatus, PaymentStatus, TOrderList } from './types';

export const MOCK_ORDERS: TOrderList[] = [
  {
    id: 'mo-1',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'John Doe',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'John Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-2',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'John Doe',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'John Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-3',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Jane Doe',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Jane Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-4',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Mark Smith',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Mark Smith',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-5',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Hannah Lewis',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Hannah Lewis',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-6',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Anna Dela Cruz',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Anna Dela Cruz',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-7',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Joshua Chang',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Joshua Chang',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-8',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Joshua Chang',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Joshua Chang',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-9',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Mary Johnson',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Mary Johnson',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-10',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'John Doe',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'John Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-11',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'John Doe',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'John Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-12',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Mary Johnson',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Mary Johnson',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-13',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Mark Smith',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Mark Smith',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-14',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Mark Smith',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Mark Smith',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-15',
    status: OrderStatus.ACTIVE,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.TO_SHIP,
    customer: 'Mark Smith',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Mark Smith',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.TO_SHIP,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-16',
    status: OrderStatus.COMPLETED,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.COMPLETED,
    customer: 'Jane Doe',
    totalPrice: 369.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Jane Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'janedoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'Neon blue/red',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 0,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.COMPLETED,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-17',
    status: OrderStatus.COMPLETED,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.COMPLETED,
    customer: 'Jane Doe',
    totalPrice: 369.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Jane Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'janedoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'Neon blue/red',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 0,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.COMPLETED,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-18',
    status: OrderStatus.COMPLETED,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.COMPLETED,
    customer: 'Jane Doe',
    totalPrice: 369.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Jane Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'janedoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'Neon blue/red',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 0,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.COMPLETED,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-19',
    status: OrderStatus.COMPLETED,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.COMPLETED,
    customer: 'Jane Doe',
    totalPrice: 369.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Jane Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'janedoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'Neon blue/red',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 0,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.COMPLETED,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-20',
    status: OrderStatus.COMPLETED,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.COMPLETED,
    customer: 'Jane Doe',
    totalPrice: 369.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'Jane Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'janedoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'Neon blue/red',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 0,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.COMPLETED,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
  {
    id: 'mo-21',
    status: OrderStatus.CANCELLED,
    createdDate: '2022-03-06T14:32:52.688Z',
    logisticStatus: LogisticStatus.CANCELLED,
    customer: 'John Doe',
    totalPrice: 269.98,
    currency: 'USD',
    paymentStatus: PaymentStatus.UNPAID,
    paymentMethod: 'Manual Bank Transfer',
    data: {
      customer: {
        customerName: 'John Doe',
        mobileNumber: '+639190911919',
        emailAddress: 'jdoe@test.com',
        address: 'Test Address, 112233',
      },
      products: {
        items: [
          {
            productName: 'Nintendo Switch OLED',
            variant: 'White',
            quantity: 1,
            price: 349.99,
            currency: 'USD',
          },
          {
            productName: 'Nintendo Switch carrying case & screen protector',
            variant: '',
            quantity: 1,
            price: 19.99,
            currency: 'USD',
          },
        ],
        deliveryFee: 5,
        discount: 100,
        currency: 'USD',
      },
      logistics: {
        logisticStatus: LogisticStatus.CANCELLED,
        recipientAddress: 'Recipient Address, 231344',
        deliveryProvider: 'DeliveryExpress',
        weight: '1kg',
        note: 'Test note',
      },
    },
  },
];
